### ISSUE TITLE
Error on installation of the last AUR build

### ISSUE THREAD

**Issue by Neo-29** [mylinuxforwork/aur#1]
![image](https://github.com/user-attachments/assets/3e3094c1-a891-493a-b508-0aca4a9120db)

As you can see on the screenshot...

Tks

**Comment by Neo-29** [comment]
That's strange.

For any reason, I emptied yay cache , restarted `ml4w-hyprland-setup`, backed up dotfiles, restarted the update, and then all went fine.

I don´t get it, but it's solved.

**Comment by mylinuxforwork** [comment]
@Neo-29 Thanks for testing and your feedback.

**Comment by Neo-29** [comment]
I have the same issue in manjaro
What I've done to solve the issue
```yay -Scc```
Yes to all

Then start again the update

Working
